[tool.poetry]
name = "odataschema2cypher"
version = "0.1.0"
description = ""
authors = ["Guy Korland <gkorland@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
